# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03ba519712268c36bc777c09f43110fef8805f449042a4b7e38eb6ea7e47996a2600fa01b1c427acbbb8e4639273bec1f7bcc5b54a3243b6ec33c0823a4c5fa5

test:
  secret_key_base: eebc6f8532e2c8950aef93fdfadb60ce8fe88a938e7fedb71409bb117f8a9676d47d10a9a4a70423ff5496d2123a08a49af4a459d8e41e772f05dfdcc0164cc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
